# Generated by Django 4.2.4 on 2023-08-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting", "Awaiting"),
                            ("in progress", "In Progress"),
                            ("finished", "Finished"),
                        ],
                        default="awaiting",
                        max_length=100,
                    ),
                ),
                (
                    "_winner",
                    models.CharField(
                        choices=[
                            ("first player", "First Player"),
                            ("second player", "Second Player"),
                        ],
                        default=None,
                        max_length=100,
                        null=True,
                    ),
                ),
                ("number_of_movements", models.PositiveIntegerField(default=0)),
                (
                    "first_player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_first_player",
                        to="core.user",
                    ),
                ),
                (
                    "second_player",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="matches_as_second_player",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
