# Generated by Django 4.2.4 on 2023-08-27 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_match"),
    ]

    operations = [
        migrations.CreateModel(
            name="Movement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("x", models.PositiveIntegerField()),
                ("y", models.PositiveIntegerField()),
                (
                    "_player",
                    models.CharField(
                        choices=[
                            ("first player", "First Player"),
                            ("second player", "Second Player"),
                        ],
                        max_length=100,
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="core.match",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.UniqueConstraint(
                fields=("x", "y", "match"), name="unique_slot_for_board"
            ),
        ),
        migrations.AddConstraint(
            model_name="movement",
            constraint=models.UniqueConstraint(
                fields=("number", "match"), name="movement_cardinality"
            ),
        ),
    ]
