name: Django Tests

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get -y install docker-compose

    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag tttdemo-web:latest

    - name: Start Docker Compose Services
      run: |
          docker-compose up -d

    - name: Run Django Tests
      run: |
        docker compose exec web python manage.py test